// autogenerated migration Version20251208215055
package migrations

import (
	"database/sql"
)

func Version20251208215055_Up(transaction *sql.Tx) error {
	sql := `
	--Autogenerated function to apply migration. Modify to your needed.
	`
	_, err := transaction.Exec(sql)
	return err
}

func Version20251208215055_Down(transaction *sql.Tx) error {
	sql := `
	--Autogenerated function to rollback migration. Modify to your needed.
	`
	_, err := transaction.Exec(sql)
	return err
}
