// autogenerated migration {version}
package migrations

import (
	"database/sql"
)

func {version}_Up(transaction *sql.Tx) error {
	sql := `
	--Autogenerated function to apply migration. Modify to your needed.
	`
	_, err := transaction.Exec(sql)
	return err
}

func {version}_Down(transaction *sql.Tx) error {
	sql := `
	--Autogenerated function to rollback migration. Modify to your needed.
	`
	_, err := transaction.Exec(sql)
	return err
}
